# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff41001c666892df906c10527e16de865ef388e9636399e8e4a350c4a8478b4cf107e16dab1d686b0b6e3f6221f72916e36ca79aff3decf3c117b5974ea330c0

test:
  secret_key_base: bdf069f55527c48b49d52a79a219c47eb4a3c3c1abed53b6099b80919263eab253d683cfc9f7ed198bc35932253895abc0085506c13eab5b567db6fbd3c90627

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
